### ISSUE TITLE
Hide runes when Runic Power above X percentage 

### ISSUE THREAD

**Issue by Alexandur11** [yivry/yrd#1]
Hello, i was trying to add a functionality to hide the frame when Runic Power goes above certain threshold, for better Runic Power management. I tend to watch the runes too much and i often waste Runic Power.

But i am making the game run poorly, lag. And also i don't achieve the hide method that i want to. 
-Using ChatGPT for my attempts. 

-If i can get some help, it would be amazing.

Good Addon.

**Comment by dmvdbrugge** [comment]
My apologies, I totally missed this issue. I no longer play and thought this would be broken by now, not realizing people actually still used it.

I can reopen this issue and try to look into it if you still want me to?

**Comment by Alexandur11** [comment]
I would say, don’t brother. I am not currently playing with the class or
the expansion.

But it still works for the expansion it was created to work, great job!
